baseURL = "http://example.org/"
disableKinds = ["section", "taxonomy", "term"]
enableEmoji = true
enableGitInfo = true
languageCode = "en-us"
pygmentsUseClasses = true
title = "@revcd"
theme = "kasparov"

[markup]
  [markup.highlight]
    tabWidth = 4
  [markup.tableOfContents]
    ordered = true

[permalinks]
  note = "/:title"
