name = "Kasparov"
license = "MIT"
licenselink = "https://github.com/revett/projects/blob/master/LICENSE"
description = ""
homepage = "http://example.com/"
tags = []
features = []
min_version = "0.41.0"

[author]
  name = "Charlie Revett"
  homepage = "https://twitter.com/revcd"
